### ISSUE TITLE
[Feat] 오픈스테이지/무대 구현

### ISSUE THREAD

**Issue by H-SeungWoo** [MTVS-VoiceTuner/VoiceTuner_Client#10]
### ISSUE

- Type: Feat
- Detail: 오픈스테이지/무대 구현. 프로토까지는 멀티를 구현하지 않고, 혼자의 경우만 재현을 함.

### TODO

- [x] 준비 시 무대 위에 배치하기
- [x] 준비 취소 시 다시 객석으로 보내기
- [x] 시작 버튼 누를 시 게임 시작
