### ISSUE TITLE
[Feat] 오픈스테이지/프론트 데스크

### ISSUE THREAD

**Issue by H-SeungWoo** [MTVS-VoiceTuner/VoiceTuner_Client#8]
### ISSUE

- Type: Feat
- Detail: 오픈스테이지/프론트 데스크 구현

### TODO

- [x] 프런트 데스크에 가면 곡 리스트 창 띄우기
- [x] UI상 곡 리스트 간단하게라도 배치해놓기
- [x] 곡 선택시 해당 노래로 세팅하기
- [x] 곡 취소시 세팅 취소
- [x] 미리듣기, 재생정지 버튼 만들고 구현하기

**Comment by H-SeungWoo** [comment]
https://www.youtube.com/watch?v=KvwHSaoAHoA
