### ISSUE TITLE
[Feat] 오픈스테이지/의자

### ISSUE THREAD

**Issue by H-SeungWoo** [MTVS-VoiceTuner/VoiceTuner_Client#9]
### ISSUE

- Type: Feat
- Detail: 오픈스테이지 구현

### TODO

- [x] 의자 근처에 갈 시 앉기 활성화
~~-[ ] 다른 사람 앉아있으면, 활성화 안되게 하기~~
- [x] 버튼 누를 시 의자에 앉기
- [x] 버튼 누를 시 의자에서 일어서기

**Comment by H-SeungWoo** [comment]
https://dev.epicgames.com/documentation/ko-kr/unreal-engine/setting-up-collisions-with-static-meshes?application_version=4.27

**Comment by H-SeungWoo** [comment]
https://makerejoicegames.tistory.com/460

**Comment by FiyeroHan** [comment]
https://dev.epicgames.com/documentation/ko-kr/unreal-engine/setting-up-collisions-with-static-meshes?application_version=4.27

**Comment by H-SeungWoo** [comment]
https://dev.epicgames.com/documentation/ko-kr/unreal-engine/BlueprintAPI/Character/Crouch?application_version=5.3

**Comment by H-SeungWoo** [comment]
다른 사람 앉아있을 시 앉기 안되는건 알파때 멀티플레이 하면서 구현할 예정
